version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nats:
    image: nats
    ports:
      - "4222:4222"

  my-app:
    build: .
    depends_on:
      - postgres
      - nats
    ports:
      - "8080:8080"
volumes:
  postgres-data:
